#include "head_std.h"
#include "head_const.h"
#include "struct_rgb.h"
#include "struct_svg.h"
#include "struct_vecs.h"
#include "struct_nodes.h"
#include "struct_hgph.h"
#include "struct_vis.h"
#include "struct_panels.h"
#include "struct_keys.h"
#include "struct_hobj.h"
#include "struct_xclient.h"

#include "func_callbackio.h"
#include "func_xclientio.h"
#include "func_drawingio.h"
#include "func_xserverio.h"
#include "func_utilitiesio.h"
