#include "head_std.h"
#include "head_const.h"
#include "struct_rgb.h"
#include "struct_svg.h"
#include "struct_vecs.h"
#include "struct_nodes.h"
#include "struct_hgph.h"

#include "func_drawing.h"
#include "func_drawingio.h"
#include "func_xserverio.h"
#include "func_voronoiio.h"
#include "func_utilitiesio.h"
