#include "head_std.h"
#include "head_const.h"

#include "struct_rgb.h"
#include "struct_svg.h"
#include "struct_nodes.h"
#include "struct_hgph.h"
#include "struct_vis.h"
#include "struct_panels.h"
#include "struct_keys.h"
#include "struct_hobj.h"
#include "struct_xclient.h"
#include "struct_hvec.h"
#include "struct_mvec.h"
#include "struct_hfactor.h"
#include "struct_mIMG.h"
#include "struct_mcr.h"

#include "func_callbackio.h"
#include "func_dynamicio.h"
#include "func_xclientio.h"
#include "func_drawingio.h"
#include "func_xserverio.h"
#include "func_utilitiesio.h"
#include "func_johnio.h"
#include "func_graphio.h"

#include "func_maxsum.h"
#include "func_sumproduct.h"
#include "func_micrscanio.h"
